version: '3.2'
services:
  database:
    image: bitnami/mariadb:10.2
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "$MARIADB_ROOT_PASSWORD"
      MARIADB_DATABASE: "$MARIADB_DATABASE"
      MARIADB_USER: "$MARIADB_USER"
      MARIADB_PASSWORD: "$MARIADB_PASSWORD"
      # this credentials are changed, don't loose your time, create .env file
    volumes:
      - ./persistence-mariadb:/bitnami
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - logvolume01:/var/log
    depends_on:
      - database
volumes:
  logvolume01: {}
